# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5230a87b9721888b3de2b09de7ec9b311312af3e51d1c220bddaeba00f0ac3b5e7e2c08d47c1eb445aea374810a4f466eeb93a0913463504adfe97fbd007cc8a

test:
  secret_key_base: 82e52379e0314e59a3f147fc87e07591edcd4fb68983a159fe6a48467d5ea3317f78556d105d2533a6873b9578cc1472740f3386e45ae45b3d3d79fd99097d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
